# syntax=docker/dockerfile:1

### label: metacog-base

## The main/first Dockerfile: 
#   install: Linux (ubuntu:22.04), python3, pip,and all needed libraries
##

# Dockerfile must start with a FROM instruction. 
# Download Linux Ubuntu as the operating system.
#   ubuntu:22.04 is an operating system. We can try with a different 
#   operating sytem. 
FROM ubuntu:22.04

# the work directory (metacogtainer) and Dockerfile_base is in this directory
WORKDIR ./

## updates and install Python
# update Linux (ubuntu:22.04). 'apt-get' is only for ubuntu update. It updates any packeges that the system ubuntu:22.04 needs
RUN apt-get update

# install python3 and pip for installing python3 libraries
RUN apt-get install -y python3 python3-pip
##

## Optional, install Cuda if GPU is needed (Model Training).
# RUN apt install -y nvidia-cuda-toolkit nvidia-cuda-toolkit-gcc
# RUN pip install nvidia-cudnn-cu11==8.6.0.163
##

# Copies 'Datasets' from your computer to the Datasets folder in the Docker Container.
COPY ./Datasets /Datasets

# Copies 'Args_Class_Module.py' from your computer (.\GitHub\Dynamic-CFAR\metacogtainer/) to the main directory in the Docker Container.
COPY ./Args_Class_Module.py /Args_Class_Module.py

# Using the requirements file, which is a list of libraries needed to run the Python scripts,
#     this command automatically installs all the requirements.
# The COPY instruction copies requirements.txt from the current dirrectory and adds them to the filesystem of the container under the same name
#   COPY stays before this RUN because RUN use requirements.txt to install all libraries
COPY ./requirements.txt /requirements.txt

# install the libraries from requirements.txt (a list of libraries needed to run the Python scripts).
RUN pip install -r requirements.txt