# syntax=docker/dockerfile:1

### label: metacog-discriminator

##  The second Dockerfile
#       Reads the radar's returns and outputs the probability distributions for each radar returns (data point)
##

# Inherits from the metacog-base Docker Image.
#   (Takes everything what metacog-base, 'Dockerfile_base', did and use it)
FROM metacog-base

# Copies 'Discriminator' from your computer (.\GitHub\Dynamic-CFAR\metacogtainer/Containers/Discriminator) to the Docker Container's (Docker_disc) main 
#   folder. After 'COPY ./Containers/Discriminator /', the main folder for Dockerfile_disc has everything fromS Discriminator (./Containers/Discriminator)
COPY ./Containers/Discriminator /

# Copies 'Datasets' from your computer to the Datasets folder in the Docker Container.
COPY ./Datasets /Datasets

# Copies 'Args_Class_Module.py' from your computer (.\GitHub\Dynamic-CFAR\metacogtainer/) to the main directory in the Docker Container.
COPY ./Args_Class_Module.py /Args_Class_Module.py

# Runs Docker_Discriminator.py that is in the main folder of the Dockerfile_disc container
#   Docker_Discriminator.py reads from the Data file specified by the Args Class and outputs distribution_tensors.csv
#       which is the probability list for each data point corresponding to the likelihood of each radar distribution.
# python3 is the specification of how to run Docker_Discriminator.py
# There can only be one CMD instruction in a Dockerfile. If you list more than one CMD then only the last CMD will take effect.
#   Do not confuse RUN with CMD. RUN actually runs a command and commits the result; CMD does not execute anything at build time, but specifies the intended # #   command for the image.
CMD ["python3", "./Docker_Discriminator.py"]