# syntax=docker/dockerfile:1

# Start your image with a node base image
FROM metacog-base

COPY ./Containers/Discriminator /
COPY ./Datasets /Datasets
COPY ./Args_Class_Module.py /Args_Class_Module.py

CMD ["python3", "./Docker_Discriminator.py"]